nohup ./fakeboiler.sh &
nohup ./boiler.sh &
nohup ./boilerless.sh &
nohup ./boilermore.sh &
nohup ./dev-fake.sh &
nohup ./dev-fake.light0.sh &
nohup ./dev-fake.light1.sh &
nohup ./dev-fake.light2.sh &
nohup ./servestatus-mqtt.sh &
